## This notebook contains all the important and basic numpy functions required for Data Science. ##

In [3]:
import numpy as np

#### a) Trigonometric Functions

In [2]:
a = np.array([0,30,45,60,90]) 

print('Sine of different angles:') 
# Convert to radians by multiplying with pi/180 
print(np.sin(a*np.pi/180)) 
print('\n')  

print('Cosine values for angles in array:') 
print(np.cos(a*np.pi/180)) 
print('\n')  

print('Tangent values for given angles:') 
print(np.tan(a*np.pi/180)) 

Sine of different angles:
[0.         0.5        0.70710678 0.8660254  1.        ]


Cosine values for angles in array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


Tangent values for given angles:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


#### b) Around function 

This is a function that returns the value rounded to the desired precision. The function takes the following parameters.

decimals parameter is used to know the number of decimals to round of the number to.  Default is 0. If negative, the integer is rounded to position to the left of the decimal point.

In [4]:
a = np.array([1.0,5.55, 123, 0.567, 25.532]) 

print('Original array:') 
print(a) 
print('\n')  

print('After rounding:') 
print(np.around(a)) 
print(np.around(a, decimals = 1)) 
print(np.around(a, decimals = -1))

Original array:
[  1.      5.55  123.      0.567  25.532]


After rounding:
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]


#### c) Floor Function

This function returns the largest integer not greater than the input parameter. The floor of the scalar x is the largest 
integer i, such that i <= x. Note that in Python, flooring always is rounded away from 0.

In [5]:
a = np.array([-1.7, 1.5, -0.2, 0.6, 10]) 

print('The given array:') 
print(a) 
print('\n')  

print('The modified array:') 
print(np.floor(a))

The given array:
[-1.7  1.5 -0.2  0.6 10. ]


The modified array:
[-2.  1. -1.  0. 10.]


#### d) Ceil Function

The ceil() function returns the ceiling of an input value, i.e. the ceil of the scalar x is the smallest integer i, 
such that i >= x.

In [6]:
a = np.array([-1.7, 1.5, -0.2, 0.6, 10]) 

print('The given array:') 
print(a) 
print('\n')  

print('The modified array:') 
print(np.ceil(a))

The given array:
[-1.7  1.5 -0.2  0.6 10. ]


The modified array:
[-1.  2. -0.  1. 10.]


#### e) Arange Function

This function prints numbers between the initial specified value till last value - 1.

In [8]:
a = np.arange(1, 10)
b = np.arange(-1, 5)
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[-1  0  1  2  3  4]


#### f) sum and add in arrays

In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

[2 4 6]


In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.sum([arr1, arr2])
print(newarr)

12


In [11]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.sum([arr1, arr2], axis=1) #summation over axis
print(newarr)

[6 6]


In [13]:
arr = np.array([1, 2, 3])
newarr = np.cumsum(arr) #cummulative sum (1, 1+2, 1+2+3)
print(newarr)

[1 3 6]
